import type { HotelVoucherColorScheme, VoucherData } from '@/lib/types'
import { registerPoppins } from './pdf-fonts'
import { capturePage2Image } from './pdf-page2-capture'
import { VOUCHER_PAGE_WIDTH } from './voucher-dimensions'
import {
  colorsToPdfRgb,
  DEFAULT_HOTEL_VOUCHER_COLORS,
  type VoucherPdfColors,
} from '@/lib/hotel-voucher-settings'

let FONT = 'helvetica'

let COLORS: VoucherPdfColors = colorsToPdfRgb(DEFAULT_HOTEL_VOUCHER_COLORS)

function applyVoucherColorScheme(scheme: HotelVoucherColorScheme) {
  COLORS = colorsToPdfRgb(scheme)
}

const MARGIN = 14
const TABLE_RADIUS = 1.5
const A4_WIDTH_MM = 210

function logoPxToMm(px: number): number {
  return (px / VOUCHER_PAGE_WIDTH) * A4_WIDTH_MM
}

function drawTopRoundedRect(doc: any, x: number, y: number, w: number, h: number, r: number) {
  r = Math.min(r, w / 2, h)
  doc.setFillColor(...COLORS.navy)
  doc.roundedRect(x, y, w, h, r, r, 'F')
  doc.rect(x, y + h - r, w, r, 'F')
}

function roundedHeaderTableHooks() {
  let headerBackgroundDrawn = false

  return {
    willDrawCell: (data: any) => {
      if (data.section === 'head') {
        data.cell.styles.fillColor = false
        data.cell.styles.lineWidth = 0
        data.cell.styles.textColor = COLORS.white

        if (data.column.index === 0 && !headerBackgroundDrawn) {
          headerBackgroundDrawn = true
          const doc = data.doc
          const margin = data.table.settings.margin
          const pageWidth = doc.internal.pageSize.getWidth()
          const x = margin.left
          const w = pageWidth - margin.left - margin.right
          drawTopRoundedRect(doc, x, data.cell.y, w, data.cell.height, TABLE_RADIUS)
        }
      }

      if (data.section === 'body') {
        data.cell.styles.textColor = COLORS.text
      }
    },
  }
}

export async function downloadVoucherPdf(data: VoucherData, colors?: HotelVoucherColorScheme) {
  applyVoucherColorScheme(colors ?? DEFAULT_HOTEL_VOUCHER_COLORS)
  const colorScheme = colors ?? DEFAULT_HOTEL_VOUCHER_COLORS
  try {
    let jsPDFModule: any
    let autoTableModule: any
    try {
      jsPDFModule = await import('jspdf')
      autoTableModule = await import('jspdf-autotable')
    } catch (e) {
      console.error('[v0] Failed to import PDF libraries:', e)
      throw new Error('PDF library not available')
    }

    const jsPDFClass = jsPDFModule.jsPDF || jsPDFModule.default || jsPDFModule
    const autoTable = autoTableModule.default || autoTableModule.autoTable

    if (!jsPDFClass) {
      throw new Error('jsPDF class not found in module')
    }

    const doc = new jsPDFClass({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    })

    const poppinsLoaded = await registerPoppins(doc)
    FONT = poppinsLoaded ? 'Poppins' : 'helvetica'

    try {
      renderPage1PDF(doc, autoTable, data)
    } catch (e) {
      console.error('[v0] Error rendering page 1:', e)
      throw e
    }

    try {
      doc.addPage()
      await addPage2FromCapture(doc, data, colorScheme)
    } catch (e) {
      console.error('[v0] Error rendering page 2:', e)
      throw e
    }

    const filename = `HV-${(data.voucher_number || 'Voucher').replace(/[^a-z0-9]/gi, '_')}.pdf`

    try {
      doc.save(filename)
    } catch (e) {
      console.error('[v0] Error saving PDF:', e)
      const pdfBlob = doc.output('blob') as Blob
      const url = URL.createObjectURL(pdfBlob)
      const link = document.createElement('a')
      link.href = url
      link.download = filename
      link.click()
      URL.revokeObjectURL(url)
    }
  } catch (error) {
    console.error('[v0] PDF generation error:', error)
    throw error
  }
}

function drawBrandBand(doc: any, pageWidth: number) {
  doc.setFillColor(...COLORS.navy)
  doc.rect(0, 0, pageWidth, 4, 'F')
  doc.setFillColor(...COLORS.gold)
  doc.rect(0, 4, pageWidth, 0.8, 'F')
}

function drawFooter(doc: any, pageWidth: number, pageHeight: number, label: string) {
  doc.setDrawColor(...COLORS.border)
  doc.setLineWidth(0.3)
  doc.line(MARGIN, pageHeight - 12, pageWidth - MARGIN, pageHeight - 12)

  doc.setFont(FONT, 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...COLORS.muted)
  doc.text(label, MARGIN, pageHeight - 8)
  doc.text('Generated by Hotel Voucher System', pageWidth - MARGIN, pageHeight - 8, { align: 'right' })
}

function drawSectionTitle(doc: any, title: string, y: number): number {
  doc.setFillColor(...COLORS.gold)
  doc.rect(MARGIN, y - 3, 1.2, 4.2, 'F')
  doc.setFont(FONT, 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...COLORS.navy)
  doc.text(title.toUpperCase(), MARGIN + 3.5, y)
  return y + 4
}

function renderPage1PDF(doc: any, autoTable: any, data: VoucherData) {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let y = 14

  drawBrandBand(doc, pageWidth)

  let headerTextX = MARGIN

  if (data.logo_show_page1 && data.logo_data) {
    try {
      const logoW = logoPxToMm(data.logo_width)
      const logoH = logoPxToMm(data.logo_height ?? 64)
      doc.addImage(data.logo_data, 'PNG', MARGIN, y - 2, logoW, logoH)
      headerTextX = MARGIN + logoW + 5
    } catch (e) {
      console.warn('[v0] Could not add logo to PDF:', e)
    }
  }

  if (data.company_name_header_show && data.company_name_header) {
    doc.setFont(FONT, 'bold')
    doc.setFontSize(17)
    doc.setTextColor(...COLORS.navy)
    doc.text(data.company_name_header, headerTextX, y + 4)
  }

  doc.setFont(FONT, 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...COLORS.gold)
  doc.text('HOTEL VOUCHER', headerTextX, y + 10.5)

  const badgeW = 52
  const badgeH = 16
  const badgeX = pageWidth - MARGIN - badgeW
  doc.setFillColor(...COLORS.navy)
  doc.roundedRect(badgeX, y - 3, badgeW, badgeH, 1.5, 1.5, 'F')
  doc.setFont(FONT, 'normal')
  doc.setFontSize(6.5)
  doc.setTextColor(200, 210, 224)
  doc.text('VOUCHER NO.', badgeX + badgeW / 2, y + 1.5, { align: 'center' })
  doc.setFont(FONT, 'bold')
  doc.setFontSize(12)
  doc.setTextColor(...COLORS.white)
  doc.text(data.voucher_number || '—', badgeX + badgeW / 2, y + 7.5, { align: 'center' })
  doc.setFont(FONT, 'normal')
  doc.setFontSize(6.5)
  doc.setTextColor(200, 210, 224)
  doc.text(`Date: ${data.voucher_date || '—'}`, badgeX + badgeW / 2, y + 11.5, { align: 'center' })

  y += 20

  doc.setDrawColor(...COLORS.border)
  doc.setLineWidth(0.3)
  doc.line(MARGIN, y, pageWidth - MARGIN, y)
  y += 6

  y = drawSectionTitle(doc, 'Booking Information', y)
  y += 2

  const infoItems: Array<[string, string]> = [
    ['Company', data.company_name_meta_show ? data.company_name_meta || '—' : '—'],
    ['Reference No.', data.reference_no || '—'],
    ['Family Head', data.family_head || '—'],
    ['Package', data.package_info || '—'],
  ]

  const cellGap = 4
  const cellW = (pageWidth - 2 * MARGIN - cellGap) / 2
  const cellH = 11

  infoItems.forEach((item, i) => {
    const col = i % 2
    const row = Math.floor(i / 2)
    const cx = MARGIN + col * (cellW + cellGap)
    const cy = y + row * (cellH + 3)

    doc.setFillColor(...COLORS.lightBg)
    doc.setDrawColor(...COLORS.border)
    doc.setLineWidth(0.2)
    doc.roundedRect(cx, cy, cellW, cellH, 1, 1, 'FD')

    doc.setFont(FONT, 'bold')
    doc.setFontSize(6.5)
    doc.setTextColor(...COLORS.muted)
    doc.text(item[0].toUpperCase(), cx + 3, cy + 4)

    doc.setFont(FONT, 'bold')
    doc.setFontSize(9.5)
    doc.setTextColor(...COLORS.text)
    doc.text(item[1], cx + 3, cy + 8.7, { maxWidth: cellW - 6 })
  })

  y += 2 * cellH + 3 + 8

  y = drawSectionTitle(doc, 'Pilgrims Details', y)
  y += 2

  const showPassport = data.pilgrims.some((p) => p.passport_show)
  const showVisa = data.pilgrims.some((p) => p.visa_show)

  const pilgrimHead = [
    '#',
    'Mutamer Name',
    ...(showPassport ? ['Passport No.'] : []),
    'Gender',
    'Pax',
    'Beds',
    ...(showVisa ? ['Visa Number'] : []),
  ]

  const pilgrimBody = data.pilgrims.map((p, i) => [
    String(i + 1),
    p.mutamer_name || '—',
    ...(showPassport ? [p.passport_show ? p.passport_no || '—' : ''] : []),
    p.gender || '—',
    String(p.pax),
    String(p.beds),
    ...(showVisa ? [p.visa_show ? p.visa_number || '—' : ''] : []),
  ])

  autoTable(doc, {
    startY: y,
    head: [pilgrimHead],
    body: pilgrimBody,
    margin: { left: MARGIN, right: MARGIN },
    theme: 'grid',
    ...roundedHeaderTableHooks(),
    styles: {
      font: FONT,
      fontSize: 8,
      cellPadding: { top: 2.2, bottom: 2.2, left: 2.5, right: 2.5 },
      textColor: COLORS.text as unknown as number[],
      lineColor: COLORS.border as unknown as number[],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: COLORS.navy as unknown as number[],
      textColor: COLORS.white as unknown as number[],
      fontStyle: 'bold',
      fontSize: 7.5,
      halign: 'left',
    },
    bodyStyles: {
      textColor: COLORS.text as unknown as number[],
    },
    alternateRowStyles: {
      fillColor: COLORS.lightBg as unknown as number[],
      textColor: COLORS.text as unknown as number[],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center', textColor: COLORS.text as unknown as number[] },
      [pilgrimHead.indexOf('Gender')]: { halign: 'center', cellWidth: 18 },
      [pilgrimHead.indexOf('Pax')]: { halign: 'center', cellWidth: 12 },
      [pilgrimHead.indexOf('Beds')]: { halign: 'center', cellWidth: 12 },
    },
  })

  y = (doc as any).lastAutoTable.finalY + 8

  y = drawSectionTitle(doc, 'Accommodation Details', y)
  y += 2

  const hotelBody = data.hotels.map((h) => {
    const checkout =
      h.checkin_date && h.nights > 0
        ? new Date(new Date(h.checkin_date).getTime() + h.nights * 24 * 60 * 60 * 1000).toLocaleDateString('en-GB')
        : '—'
    return [
      h.hotel_name || '—',
      h.confirmation_no || '—',
      h.city || '—',
      h.room_type || '—',
      h.meal_plan || '—',
      h.checkin_date || '—',
      checkout,
      String(h.nights),
    ]
  })

  autoTable(doc, {
    startY: y,
    head: [['Hotel Name', 'Confirm No.', 'City', 'Room Type', 'Meal', 'Check In', 'Check Out', 'Nights']],
    body: hotelBody,
    margin: { left: MARGIN, right: MARGIN },
    theme: 'grid',
    ...roundedHeaderTableHooks(),
    styles: {
      font: FONT,
      fontSize: 7.5,
      cellPadding: { top: 2.2, bottom: 2.2, left: 2, right: 2 },
      textColor: COLORS.text as unknown as number[],
      lineColor: COLORS.border as unknown as number[],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: COLORS.navy as unknown as number[],
      textColor: COLORS.white as unknown as number[],
      fontStyle: 'bold',
      fontSize: 7,
      halign: 'left',
    },
    bodyStyles: {
      textColor: COLORS.text as unknown as number[],
    },
    alternateRowStyles: {
      fillColor: COLORS.lightBg as unknown as number[],
      textColor: COLORS.text as unknown as number[],
    },
    columnStyles: {
      0: { textColor: COLORS.text as unknown as number[] },
      1: { halign: 'center' },
      2: { halign: 'center' },
      4: { halign: 'center' },
      5: { halign: 'center' },
      6: { halign: 'center' },
      7: { halign: 'center', cellWidth: 12 },
    },
  })

  y = (doc as any).lastAutoTable.finalY + 8

  const contacts: Array<[string, string]> = []
  if (data.makkah_hotel_contact) contacts.push(['Makkah Hotel', data.makkah_hotel_contact])
  if (data.madinah_hotel_contact) contacts.push(['Madinah Hotel', data.madinah_hotel_contact])
  if (data.makkah_transport_contact) contacts.push(['Makkah Transport', data.makkah_transport_contact])
  if (data.madinah_transport_contact) contacts.push(['Madinah Transport', data.madinah_transport_contact])
  if (data.jeddah_transport_contact) contacts.push(['Jeddah Transport', data.jeddah_transport_contact])

  if (contacts.length > 0 || data.checkin_time || data.checkout_time) {
    y = drawSectionTitle(doc, 'Contacts & Timing', y)
    y += 2

    const colW = (pageWidth - 2 * MARGIN - cellGap) / 2
    contacts.forEach((c, i) => {
      const col = i % 2
      const row = Math.floor(i / 2)
      const cx = MARGIN + col * (colW + cellGap)
      const cy = y + row * 6

      doc.setFont(FONT, 'bold')
      doc.setFontSize(8)
      doc.setTextColor(...COLORS.muted)
      doc.text(`${c[0]}:`, cx, cy + 3)

      doc.setFont(FONT, 'normal')
      doc.setTextColor(...COLORS.text)
      doc.text(c[1], cx + 32, cy + 3, { maxWidth: colW - 33 })
    })

    y += Math.ceil(contacts.length / 2) * 6 + 3

    if (data.checkin_time || data.checkout_time) {
      doc.setFillColor(...COLORS.lightBg)
      doc.setDrawColor(...COLORS.border)
      doc.setLineWidth(0.2)
      doc.roundedRect(MARGIN, y, pageWidth - 2 * MARGIN, 8, 1, 1, 'FD')
      doc.setFont(FONT, 'bold')
      doc.setFontSize(8.5)
      doc.setTextColor(...COLORS.navy)
      doc.text(
        `Check-In Time: ${data.checkin_time || '—'}     |     Check-Out Time: ${data.checkout_time || '—'}`,
        pageWidth / 2,
        y + 5.3,
        { align: 'center' },
      )
      y += 12
    }
  }

  const noteY = Math.max(y + 2, pageHeight - 26)
  doc.setDrawColor(...COLORS.gold)
  doc.setLineWidth(0.4)
  doc.setFillColor(...COLORS.noteBg)
  doc.roundedRect(MARGIN, noteY, pageWidth - 2 * MARGIN, 9, 1, 1, 'FD')
  doc.setFont(FONT, 'bold')
  doc.setFontSize(8.5)
  doc.setTextColor(...COLORS.gold)
  doc.text('NOTE: THIS BOOKING WILL NOT REFUND, NOT CHANGE', pageWidth / 2, noteY + 5.8, { align: 'center' })

  drawFooter(doc, pageWidth, pageHeight, `Voucher ${data.voucher_number || ''} — Page 1 of 2`)
}

async function addPage2FromCapture(doc: any, data: VoucherData, colors: HotelVoucherColorScheme) {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const imgData = await capturePage2Image(data, colors)
  doc.addImage(imgData, 'PNG', 0, 0, pageWidth, pageHeight, undefined, 'FAST')
}
