'use client'

import { useEffect, useRef, useState } from 'react'
import type { HotelVoucherColorScheme, VoucherData } from '@/lib/types'
import { VoucherColorsProvider, useVoucherColors } from './voucher-colors-context'
import { VOUCHER_PAGE_HEIGHT, VOUCHER_PAGE_WIDTH } from './voucher-dimensions'

interface PreviewProps {
  data: VoucherData
  page: 1 | 2
  colors?: HotelVoucherColorScheme
}

const URDU_FONT = 'var(--font-urdu), "Noto Nastaliq Urdu", "Segoe UI", "Arial Unicode MS", sans-serif'
const GUIDELINES_FONT = '"Jameel Noori Nastaleeq", "Noto Nastaliq Urdu", "Segoe UI", serif'
const COMPANY_FONT = 'system-ui, -apple-system, sans-serif'

function voucherLogoStyle(data: VoucherData): React.CSSProperties {
  return {
    width: `${data.logo_width}px`,
    height: `${data.logo_height ?? 64}px`,
    objectFit: 'contain',
    flexShrink: 0,
  }
}

function ScaledVoucherFrame({ children }: { children: React.ReactNode }) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [scale, setScale] = useState(1)

  useEffect(() => {
    const el = containerRef.current
    if (!el) return

    const update = () => {
      const width = el.getBoundingClientRect().width
      if (width > 0) setScale(width / VOUCHER_PAGE_WIDTH)
    }

    update()
    const ro = new ResizeObserver(update)
    ro.observe(el)
    return () => ro.disconnect()
  }, [])

  const scaledHeight = VOUCHER_PAGE_HEIGHT * scale

  return (
    <div ref={containerRef} className="flex w-full justify-center">
      <div
        className="overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black/5"
        style={{ width: '100%', height: scaledHeight }}
      >
        <div
          style={{
            width: VOUCHER_PAGE_WIDTH,
            height: VOUCHER_PAGE_HEIGHT,
            transform: `scale(${scale})`,
            transformOrigin: 'top left',
          }}
        >
          {children}
        </div>
      </div>
    </div>
  )
}

export function VoucherPreview({ data, page, colors }: PreviewProps) {
  useEffect(() => {
    if (page === 2) {
      void document.fonts.load('18px "Jameel Noori Nastaleeq"')
      void document.fonts.load('14px "Noto Nastaliq Urdu"')
    }
  }, [page])

  const pageContent = page === 1 ? (
    <div className="flex justify-center">
      <div
        className="w-full overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black/5"
        style={{ aspectRatio: '595 / 842', maxWidth: '100%' }}
      >
        <Page1 data={data} />
      </div>
    </div>
  ) : (
    <ScaledVoucherFrame>
      <VoucherPage2 data={data} />
    </ScaledVoucherFrame>
  )

  if (colors) {
    return <VoucherColorsProvider colors={colors}>{pageContent}</VoucherColorsProvider>
  }

  return pageContent
}

function BrandBand() {
  const C = useVoucherColors()
  return (
    <div>
      <div style={{ height: '6px', backgroundColor: C.navy }} />
      <div style={{ height: '1.5px', backgroundColor: C.gold }} />
    </div>
  )
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  const C = useVoucherColors()
  return (
    <div className="mb-2 flex items-center gap-2">
      <div style={{ width: '3px', height: '12px', backgroundColor: C.gold }} />
      <div
        style={{
          fontSize: '10px',
          fontWeight: 700,
          letterSpacing: '0.08em',
          textTransform: 'uppercase',
          color: C.navy,
        }}
      >
        {children}
      </div>
    </div>
  )
}

function InfoCell({ label, value }: { label: string; value: string }) {
  const C = useVoucherColors()
  return (
    <div
      style={{
        backgroundColor: C.lightBg,
        border: `1px solid ${C.border}`,
        borderRadius: '4px',
        padding: '6px 8px',
      }}
    >
      <div style={{ fontSize: '7px', fontWeight: 700, letterSpacing: '0.06em', color: C.muted, textTransform: 'uppercase' }}>
        {label}
      </div>
      <div style={{ fontSize: '10px', fontWeight: 700, color: C.text, marginTop: '2px' }}>{value}</div>
    </div>
  )
}

function Footer({ label }: { label: string }) {
  const C = useVoucherColors()
  return (
    <div
      style={{
        borderTop: `1px solid ${C.border}`,
        paddingTop: '6px',
        display: 'flex',
        justifyContent: 'space-between',
        fontSize: '7px',
        color: C.muted,
      }}
    >
      <span>{label}</span>
      <span>Generated by Hotel Voucher System</span>
    </div>
  )
}

function Page1({ data }: { data: VoucherData }) {
  const C = useVoucherColors()
  const showPassport = data.pilgrims.some((p) => p.passport_show)
  const showVisa = data.pilgrims.some((p) => p.visa_show)

  const th: React.CSSProperties = {
    backgroundColor: C.navy,
    color: '#FFFFFF',
    fontWeight: 700,
    fontSize: '8px',
    textAlign: 'left',
    padding: '5px 6px',
    border: 'none',
    borderRight: '1px solid rgba(255,255,255,0.12)',
  }

  const tableWrap: React.CSSProperties = {
    borderRadius: '6px',
    overflow: 'hidden',
    border: `1px solid ${C.border}`,
  }

  const td = (alt: boolean): React.CSSProperties => ({
    border: `1px solid ${C.border}`,
    padding: '5px 6px',
    color: C.text,
    backgroundColor: alt ? C.lightBg : '#FFFFFF',
  })

  return (
    <div className="flex h-full w-full flex-col bg-white" style={{ fontFamily: COMPANY_FONT, fontSize: '10px', color: C.text }}>
      <BrandBand />
      <div className="flex flex-1 flex-col overflow-hidden p-7">
        {/* Header */}
        <div className="mb-4 flex items-start justify-between gap-4">
          <div className="flex items-start gap-3">
            {data.logo_show_page1 && (
              data.logo_data ? (
                <img src={data.logo_data} alt="Logo" style={voucherLogoStyle(data)} />
              ) : (
              <div style={{ width: `${data.logo_width}px`, flexShrink: 0 }}>
                  <div
                    style={{
                      height: `${data.logo_height ?? 64}px`,
                      backgroundColor: C.lightBg,
                      border: `1px dashed ${C.border}`,
                      borderRadius: '4px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      color: C.muted,
                      fontSize: '8px',
                    }}
                  >
                    LOGO
                  </div>
              </div>
              )
            )}
            <div>
              {data.company_name_header_show && (
                <div style={{ fontSize: '18px', fontWeight: 800, lineHeight: 1.15, color: C.navy, fontFamily: COMPANY_FONT }}>
                  {data.company_name_header}
                </div>
              )}
              <div style={{ fontSize: '10px', fontWeight: 700, letterSpacing: '0.14em', color: C.gold, marginTop: '3px' }}>
                HOTEL VOUCHER
              </div>
            </div>
          </div>

          {/* Voucher badge */}
          <div
            style={{
              backgroundColor: C.navy,
              borderRadius: '6px',
              padding: '7px 14px',
              textAlign: 'center',
              flexShrink: 0,
            }}
          >
            <div style={{ fontSize: '6.5px', letterSpacing: '0.1em', color: '#C8D2E0' }}>VOUCHER NO.</div>
            <div style={{ fontSize: '13px', fontWeight: 800, color: '#FFFFFF', margin: '2px 0' }}>
              {data.voucher_number || '—'}
            </div>
            <div style={{ fontSize: '7px', color: '#C8D2E0' }}>Date: {data.voucher_date || '—'}</div>
          </div>
        </div>

        <div style={{ borderTop: `1px solid ${C.border}`, marginBottom: '12px' }} />

        {/* Booking information */}
        <div className="mb-4">
          <SectionTitle>Booking Information</SectionTitle>
          <div className="grid grid-cols-2 gap-2">
            <InfoCell label="Company" value={data.company_name_meta_show ? data.company_name_meta || '—' : '—'} />
            <InfoCell label="Reference No." value={data.reference_no || '—'} />
            <InfoCell label="Family Head" value={data.family_head || '—'} />
            <InfoCell label="Package" value={data.package_info || '—'} />
          </div>
        </div>

        {/* Pilgrims Table */}
        <div className="mb-4">
          <SectionTitle>Pilgrims Details</SectionTitle>
          <div style={tableWrap}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '8.5px' }}>
            <thead>
              <tr>
                <th style={{ ...th, width: '20px', textAlign: 'center' }}>#</th>
                <th style={th}>Mutamer Name</th>
                {showPassport && <th style={th}>Passport No.</th>}
                <th style={{ ...th, textAlign: 'center' }}>Gender</th>
                <th style={{ ...th, textAlign: 'center' }}>Pax</th>
                <th style={{ ...th, textAlign: 'center', ...(!showVisa ? { borderRight: 'none' } : {}) }}>Beds</th>
                {showVisa && <th style={{ ...th, borderRight: 'none' }}>Visa Number</th>}
              </tr>
            </thead>
            <tbody>
              {data.pilgrims.map((p, i) => (
                <tr key={p.id}>
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>{i + 1}</td>
                  <td style={{ ...td(i % 2 === 1), fontWeight: 600 }}>{p.mutamer_name || '—'}</td>
                  {showPassport && <td style={td(i % 2 === 1)}>{p.passport_show ? p.passport_no || '—' : ''}</td>}
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>{p.gender}</td>
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>{p.pax}</td>
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>{p.beds}</td>
                  {showVisa && <td style={td(i % 2 === 1)}>{p.visa_show ? p.visa_number || '—' : ''}</td>}
                </tr>
              ))}
            </tbody>
          </table>
          </div>
        </div>

        {/* Accommodation Table */}
        <div className="mb-4">
          <SectionTitle>Accommodation Details</SectionTitle>
          <div style={tableWrap}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '8px' }}>
            <thead>
              <tr>
                <th style={th}>Hotel Name</th>
                <th style={{ ...th, textAlign: 'center' }}>Confirm No.</th>
                <th style={{ ...th, textAlign: 'center' }}>City</th>
                <th style={th}>Room Type</th>
                <th style={{ ...th, textAlign: 'center' }}>Meal</th>
                <th style={{ ...th, textAlign: 'center' }}>Check In</th>
                <th style={{ ...th, textAlign: 'center' }}>Check Out</th>
                <th style={{ ...th, textAlign: 'center', borderRight: 'none' }}>Nights</th>
              </tr>
            </thead>
            <tbody>
              {data.hotels.map((h, i) => (
                <tr key={h.id}>
                  <td style={{ ...td(i % 2 === 1), fontWeight: 600 }}>{h.hotel_name || '—'}</td>
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>{h.confirmation_no || '—'}</td>
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>{h.city}</td>
                  <td style={td(i % 2 === 1)}>{h.room_type}</td>
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>{h.meal_plan}</td>
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>{h.checkin_date || '—'}</td>
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>
                    {h.checkin_date && h.nights > 0
                      ? new Date(new Date(h.checkin_date).getTime() + h.nights * 24 * 60 * 60 * 1000).toLocaleDateString('en-GB')
                      : '—'}
                  </td>
                  <td style={{ ...td(i % 2 === 1), textAlign: 'center' }}>{h.nights}</td>
                </tr>
              ))}
            </tbody>
          </table>
          </div>
        </div>

        {/* Contacts & Timing */}
        <div className="mb-3">
          <SectionTitle>Contacts &amp; Timing</SectionTitle>
          <div className="grid grid-cols-2 gap-x-4 gap-y-1" style={{ fontSize: '8.5px' }}>
            {data.makkah_hotel_contact && (
              <div>
                <span style={{ fontWeight: 700, color: C.muted }}>Makkah Hotel: </span>
                {data.makkah_hotel_contact}
              </div>
            )}
            {data.madinah_hotel_contact && (
              <div>
                <span style={{ fontWeight: 700, color: C.muted }}>Madinah Hotel: </span>
                {data.madinah_hotel_contact}
              </div>
            )}
            {data.makkah_transport_contact && (
              <div>
                <span style={{ fontWeight: 700, color: C.muted }}>Makkah Transport: </span>
                {data.makkah_transport_contact}
              </div>
            )}
            {data.madinah_transport_contact && (
              <div>
                <span style={{ fontWeight: 700, color: C.muted }}>Madinah Transport: </span>
                {data.madinah_transport_contact}
              </div>
            )}
            {data.jeddah_transport_contact && (
              <div>
                <span style={{ fontWeight: 700, color: C.muted }}>Jeddah Transport: </span>
                {data.jeddah_transport_contact}
              </div>
            )}
          </div>
          {(data.checkin_time || data.checkout_time) && (
            <div
              style={{
                marginTop: '6px',
                backgroundColor: C.lightBg,
                border: `1px solid ${C.border}`,
                borderRadius: '4px',
                padding: '5px',
                textAlign: 'center',
                fontWeight: 700,
                fontSize: '8.5px',
                color: C.navy,
              }}
            >
              Check-In Time: {data.checkin_time || '—'} &nbsp;|&nbsp; Check-Out Time: {data.checkout_time || '—'}
            </div>
          )}
        </div>

        {/* Important note */}
        <div className="mt-auto">
          <div
            style={{
              backgroundColor: C.noteBg,
              border: `1px solid ${C.gold}`,
              borderRadius: '4px',
              padding: '6px',
              textAlign: 'center',
              fontWeight: 700,
              fontSize: '8.5px',
              color: C.gold,
              marginBottom: '8px',
            }}
          >
            NOTE: THIS BOOKING WILL NOT REFUND, NOT CHANGE
          </div>
          <Footer label={`Voucher ${data.voucher_number || ''} — Page 1 of 2`} />
        </div>
      </div>
    </div>
  )
}

export function VoucherPage2({ data }: { data: VoucherData }) {
  const C = useVoucherColors()
  const guidelines = data.guidelines_urdu
    .split('\n')
    .map((line) => line.replace(/^\s*\d+[\.\)]\s*/, '').trim())
    .filter(Boolean)

  return (
    <div
      className="flex flex-col bg-white"
      style={{ fontFamily: URDU_FONT, color: C.text, width: VOUCHER_PAGE_WIDTH, height: VOUCHER_PAGE_HEIGHT }}
    >
      <BrandBand />
      <div className="flex flex-1 flex-col overflow-hidden p-7">
        {/* Header */}
        <div className="mb-3 flex items-start justify-between gap-4">
          <div style={{ flexShrink: 0 }}>
            {data.logo_show_page2 && data.logo_data ? (
              <img src={data.logo_data} alt="Logo" style={voucherLogoStyle(data)} />
            ) : (
              data.company_name_header_show &&
              data.company_name_header && (
                <div style={{ fontSize: '26px', fontWeight: 800, lineHeight: 1.15, color: C.navy, maxWidth: '220px', fontFamily: COMPANY_FONT }}>
                  {data.company_name_header}
                </div>
              )
            )}
          </div>
          <div className="text-right">
            <div style={{ fontSize: '24px', fontWeight: 800, color: C.navy }}>ضروری ہدایات</div>
            <div style={{ fontSize: '12px', color: C.muted, marginTop: '2px' }}>Important Guidelines</div>
          </div>
        </div>

        <div style={{ borderTop: `1px solid ${C.border}`, marginBottom: '12px' }} />

        {/* Guidelines */}
        <div
          className="flex-1 overflow-hidden"
          style={{ direction: 'rtl', textAlign: 'right', fontSize: '18px', lineHeight: 1.7, fontFamily: GUIDELINES_FONT }}
        >
          {guidelines.map((line, idx) => (
            <div
              key={idx}
              style={{
                display: 'grid',
                gridTemplateColumns: '18px 1fr',
                gap: '10px',
                alignItems: 'center',
                direction: 'rtl',
                marginBottom: '8px',
              }}
            >
              <span
                style={{
                  color: C.navy,
                  fontWeight: 700,
                  fontSize: '14px',
                  fontFamily: COMPANY_FONT,
                  direction: 'ltr',
                  unicodeBidi: 'isolate',
                  lineHeight: 1.7,
                  textAlign: 'center',
                }}
              >
                {idx + 1}
              </span>
              <span style={{ fontFamily: GUIDELINES_FONT, lineHeight: 1.7, textAlign: 'right', direction: 'rtl' }}>
                {line}
              </span>
            </div>
          ))}
        </div>

        {/* Acknowledgement & Signature */}
        <div className="mt-auto">
          <div
            style={{
              backgroundColor: C.lightBg,
              border: `1px solid ${C.border}`,
              borderRadius: '6px',
              padding: '14px',
              marginBottom: '8px',
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
              gap: '20px',
            }}
          >
            <div style={{ flexShrink: 0, textAlign: 'center' }}>
              <div style={{ borderTop: `1px solid ${C.text}`, width: '120px', marginBottom: '3px', marginTop: '1.5em' }} />
              <div style={{ fontSize: '8px', color: C.muted, fontFamily: URDU_FONT }}>دستخط / SIGN</div>
            </div>
            <div
              style={{
                flex: 1,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'flex-end',
                textAlign: 'right',
              }}
            >
              <span
                style={{
                  fontSize: '18px',
                  fontWeight: 700,
                  fontFamily: GUIDELINES_FONT,
                  direction: 'rtl',
                  lineHeight: 1,
                  display: 'inline-block',
                  marginBottom: '1em',
                }}
              >
                میں نے ان تمام ہدایات کو پڑھا ہے اور ان پر عمل کرنے کا عہد کرتا ہوں
              </span>
            </div>
          </div>
          <Footer label={`Voucher ${data.voucher_number || ''} — Page 2 of 2`} />
        </div>
      </div>
    </div>
  )
}
